### ISSUE TITLE
Unable to invoke the table.

### ISSUE THREAD

**Issue by ZaidMomin1** [Citytechinc/promised-dynamo#2]
I have the below code 
var dynamodb = new require('promised-dynamo')({
    accessKeyId: "xyz",
    secretAccessKey: "abc",
    region: "eu-west-1"
}, ['masterTable']);

When I invoke the method using the below code:
dynamodb.masterTable.putItem({
        fid: 88,
        task: "Pull",
        time: "12:10"
    }
    .then(function(response) {
        console.log(JSON.stringify(result.item));
    })

I get an error:
dynamodb.masterTable.putItem({
                 ^
TypeError: Cannot read property 'masterTable' of undefined

**Comment by pmichelotti** [comment]
Hi @ZaidMomin1 - can you confirm whether you are using the latest version, `0.12.0` (or if not which release you are using)?

**Comment by ZaidMomin1** [comment]
Hi @pmichelotti Yes I'm using the latest version(0.12.0)

**Comment by pmichelotti** [comment]
Hi @ZaidMomin1 - there is an error in the readme (which I've updated in the develop branch).  In order to instantiate promised-dynamo in the way originally specified in the readme it would be:

```
var dynamodb = new ( require( 'promised-dynamo' ) ) ( {
  accessKeyId: "xyz",
  secretAccessKey: "abc",
  region: "eu-west-1"
}, [ 'masterTable' ] );
```

Note the extra parentheses around the require statement.  I actually updated the readme to separate the require and the instantiation into two clearly distinct statements but this shouldn't be technically necessary.

Thanks for calling this out!
